# Generated by Django 5.0.1 on 2024-02-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSitio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
